## Running RetinaRegNet on Google Colab

### This script provides a quick guide for running our Retinal Registration model, *RetinaRegNet*, on Google Colab, addressing Python version discrepancies.


In [ ]:
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh # downloading miniconda
!bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local # installing minconda under the local folder

--2025-02-11 20:14:46--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.191.158, 104.16.32.241, 2606:4700::6810:20f1, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.191.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154615620 (147M) [application/octet-stream]
Saving to: ‘Miniconda3-latest-Linux-x86_64.sh’

Miniconda3-latest-L 100%[===================>] 147.45M  81.1MB/s    in 1.8s    

2025-02-11 20:14:48 (81.1 MB/s) - ‘Miniconda3-latest-Linux-x86_64.sh’ saved [154615620/154615620]

PREFIX=/usr/local
Unpacking payload ...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHON

In [ ]:
!conda init bash # initializing conda using bash commands

no change     /usr/local/condabin/conda
no change     /usr/local/bin/conda
no change     /usr/local/bin/conda-env
no change     /usr/local/bin/activate
no change     /usr/local/bin/deactivate
no change     /usr/local/etc/profile.d/conda.sh
no change     /usr/local/etc/fish/conf.d/conda.fish
no change     /usr/local/shell/condabin/Conda.psm1
no change     /usr/local/shell/condabin/conda-hook.ps1
no change     /usr/local/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /usr/local/etc/profile.d/conda.csh
modified      /root/.bashrc

==> For changes to take effect, close and re-open your current shell. <==



In [ ]:
!conda create --name my_env python=3.10.12 -y # creating a virtual enviroment with python version 3.10.12 using conda

Channels:
 - defaults
Platform: linux-64
Solving environment: - done

## Package Plan ##

  environment location: /usr/local/envs/my_env

  added / updated specs:
    - python=3.10.12


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-25.0                   |  py310h06a4308_0         2.3 MB
    python-3.10.12             |       h955ad1f_0        26.8 MB
    setuptools-75.8.0          |  py310h06a4308_0         1.6 MB
    wheel-0.45.1               |  py310h06a4308_0         115 KB
    ------------------------------------------------------------
                                           Total:        30.9 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6 
  ca-certificates    pkgs/main/lin

In [ ]:
!conda info --envs # checking to see if the newly created conda environemnt is setup sucessfully


# conda environments:
#
base                   /usr/local
my_env                 /usr/local/envs/my_env



In [ ]:
!conda install -n my_env jupyter ipykernel -y # installing the jupyter and ipykernel pacakges in the new conda environment to avoid any run time errors during code execution , especially since the python script is generated form the original hupyter notebook

Channels:
 - defaults
Platform: linux-64
Solving environment: - \ done

## Package Plan ##

  environment location: /usr/local/envs/my_env

  added / updated specs:
    - ipykernel
    - jupyter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anyio-4.6.2                |  py310h06a4308_0         204 KB
    argon2-cffi-21.3.0         |     pyhd3eb1b0_0          15 KB
    argon2-cffi-bindings-21.2.0|  py310h5eee18b_1          32 KB
    asttokens-2.0.5            |     pyhd3eb1b0_0          20 KB
    async-lru-2.0.4            |  py310h06a4308_0          18 KB
    attrs-24.3.0               |  py310h06a4308_0         152 KB
    babel-2.16.0               |  py310h06a4308_0         6.8 MB
    beautifulsoup4-4.12.3      |  py310h06a4308_0         220 KB
    bleach-6.2.0               |  py310h06a4308_0         300 KB
    brotli-python-1.0.9        |  py310h6a678d5_9         356 KB
    c

In [ ]:
!source activate my_env # Activating the new conda environemnt

In [ ]:
!source activate my_env && pip install -r requirements.txt # Installing the list of packages listed under the requirements.txt file

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 989.1/989.1 kB 9.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 135.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.2/77.2 MB 57.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 136.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.6/211.6 MB 62.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 177.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 50.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 MB 65.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 150.0 MB/s eta

In [ ]:
!source activate my_env && pip install patool==3.1.0 # installing the

In [ ]:
!source activate my_env && python <name_of_script>.py # executing the python script through the conda environment

Extracted FIRE.7z into /content/
Created 3 Sub Folders for saving Registration Results
Case 0
Loading Fixed Images /content/FIRE/Images/A01_1.jpg Moving Image/content/FIRE/Images/A01_2.jpg to the framework
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]






Fetching 11 files:   9% 1/11 [00:00<00:02,  4.00it/s]






























































Fetching 11 files: 100% 11/11 [00:28<00:00,  2.55s/it]
Loading pipeline components...: 100% 6/6 [00:00<00:00, 12.49it/s]
/content/retinaregnet_fire_evaluation_script.py:441: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  points_indices = torch.tensor(pts_list)
Figure(1200x600)
Homography Matrix:
[[ 9.91852312e-01  6.48639960e-02 -1.73058537e+01]
 [-7.06080243e-02  9.95262260e-01  1.25102579e+01]
 [-2.50725688e-05 -3.42649284e-06  1.00000000e+00]]
Figure(1800x600)
Loading